name: "ci build"
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, ready_for_review, reopened ]
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: write

env:
  REGISTRY: 123456789012.dkr.ecr.eu-west-1.amazonaws.com
  SERVICE_NAME: ${{ github.event.repository.name }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
    - uses: olafurpg/setup-scala@v14
      with:
        java-version: adopt@1.11

    - name: Extract metadata (tags, labels) for service image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.SERVICE_NAME }}
        tags: |
          type=ref,event=branch,suffix=-{{sha}}
  
    - name: Run tests
      env:
        BUILD_VERSION: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
      run: |
        sbt test
      # sbt test stage
      
    - uses: sbt/setup-sbt@v1
    - uses: scalacenter/sbt-dependency-submission@v2

#    - name: Set up Docker Buildx
#      uses: docker/setup-buildx-action@v3
#
#    - name: Configure AWS credentials
#      if: github.ref == 'refs/heads/master'
#      uses: aws-actions/configure-aws-credentials@v1
#      with:
#        aws-region: eu-west-1
#        role-to-assume: ${{ env.AWS_ROLE }}
#        role-duration-seconds: 1200
#
#    - name: Log in to the ECR
#      if: github.event_name != 'pull_request'
#      uses: docker/login-action@v3
#      with:
#        registry: ${{ env.AWS_ECR }}
#
#    - name: Build and push service image
#      uses: docker/build-push-action@v5
#      with:
#        push: ${{ github.event_name != 'pull_request' }}
#        tags:   ${{ steps.meta.outputs.tags }}
#        labels: ${{ steps.meta.outputs.labels }}
#
#    - name: Tag built version
#      if: github.ref == 'refs/heads/master'
#      env:
#        TAG_VALUE: ${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
#      run: |
#        git tag $TAG_VALUE $GITHUB_SHA
#        git push origin $TAG_VALUE
